-- Tabla: Talla
CREATE TABLE Talla (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    descripciontalla VARCHAR(100) NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: Categoria
CREATE TABLE Categoria (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    descripcioncategoria VARCHAR(100) NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: Ropa
CREATE TABLE Ropa (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    descripcion VARCHAR(255) NOT NULL,
    idtalla INT UNSIGNED NOT NULL,
    idcategoria INT UNSIGNED NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idtalla) REFERENCES Talla(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idcategoria) REFERENCES Categoria(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: Tienda
CREATE TABLE Tienda (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    descripciontienda VARCHAR(255) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    telefono VARCHAR(15) NOT NULL,
    correo VARCHAR(255) NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: Stock
CREATE TABLE Stock (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idtienda INT UNSIGNED NOT NULL,
    idropa INT UNSIGNED NOT NULL,
    cantidadexistencia INT NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idtienda) REFERENCES Tienda(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idropa) REFERENCES Ropa(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: TipoComprobante
CREATE TABLE TipoComprobante (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    descripciontipocomprobante VARCHAR(255) NOT NULL,
    esventa BOOLEAN NOT NULL,
    escompra BOOLEAN NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: Timbrado
CREATE TABLE Timbrado (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idtipocomprobante INT UNSIGNED NOT NULL,
    iniciovigencia DATE NOT NULL,
    finvigencia DATE NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idtipocomprobante) REFERENCES TipoComprobante(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: Proveedor
CREATE TABLE Proveedor (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    razonsocial VARCHAR(255) NOT NULL,
    nombre VARCHAR(100),
    apellido VARCHAR(100),
    ruc VARCHAR(20) NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: PedidoCompra
CREATE TABLE PedidoCompra (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nropedido VARCHAR(50) NOT NULL,
    idproveedor INT UNSIGNED NOT NULL,
    idtienda INT UNSIGNED NOT NULL,
    fechapedido DATE NOT NULL,
    estado INT NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idproveedor) REFERENCES Proveedor(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idtienda) REFERENCES Tienda(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: DetallePedidoCompra
CREATE TABLE DetallePedidoCompra (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idpedidocompra INT UNSIGNED NOT NULL,
    idropa INT UNSIGNED NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    cantidad INT NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idpedidocompra) REFERENCES PedidoCompra(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idropa) REFERENCES Ropa(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: FacturaCompra
CREATE TABLE FacturaCompra (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idpedidocompra INT UNSIGNED NOT NULL,
    fechafactura DATE NOT NULL,
    idtimbrado INT UNSIGNED NOT NULL,
    estado INT NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultimamodifcacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idpedidocompra) REFERENCES PedidoCompra(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idtimbrado) REFERENCES Timbrado(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: DetalleFacturaCompra
CREATE TABLE DetalleFacturaCompra (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idfacturacompra INT UNSIGNED NOT NULL,
    idropa INT UNSIGNED NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    cantidad INT NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idfacturacompra) REFERENCES FacturaCompra(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idropa) REFERENCES Ropa(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: Cliente
CREATE TABLE Cliente (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    razonsocial VARCHAR(255) NOT NULL,
    nombre VARCHAR(100),
    apellido VARCHAR(100),
    ruc VARCHAR(20) NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: PedidoVenta
CREATE TABLE PedidoVenta (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idcliente INT UNSIGNED NOT NULL,
    idtienda INT UNSIGNED NOT NULL,
    fechapedido DATE NOT NULL,
    estado INT NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idcliente) REFERENCES Cliente(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idtienda) REFERENCES Tienda(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: DetallePedidoVenta
CREATE TABLE DetallePedidoVenta (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idpedidoventa INT UNSIGNED NOT NULL,
    idropa INT UNSIGNED NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    cantidad INT NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idpedidoventa) REFERENCES PedidoVenta(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idropa) REFERENCES Ropa(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: FacturaVenta
CREATE TABLE FacturaVenta (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idpedidoventa INT UNSIGNED NOT NULL,
    fechafactura DATE NOT NULL,
    idtimbrado INT UNSIGNED NOT NULL,
    estado INT NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idpedidoventa) REFERENCES PedidoVenta(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idtimbrado) REFERENCES Timbrado(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: DetalleFacturaVenta
CREATE TABLE DetalleFacturaVenta (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idfacturaventa INT UNSIGNED NOT NULL,
    idropa INT UNSIGNED NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    cantidad INT NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idfacturaventa) REFERENCES FacturaVenta(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idropa) REFERENCES Ropa(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: Stock
CREATE TABLE Stock (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idtienda INT UNSIGNED NOT NULL,
    idropa INT UNSIGNED NOT NULL,
    cantidadexistencia INT NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idtienda) REFERENCES Tienda(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idropa) REFERENCES Ropa(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: TipoComprobante
CREATE TABLE TipoComprobante (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    descripciontipocomprobante VARCHAR(255) NOT NULL,
    esventa BOOLEAN NOT NULL,
    escompra BOOLEAN NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: Timbrado
CREATE TABLE Timbrado (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idtipocomprobante INT UNSIGNED NOT NULL,
    iniciovigencia DATE NOT NULL,
    finvigencia DATE NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idtipocomprobante) REFERENCES TipoComprobante(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: Proveedor
CREATE TABLE Proveedor (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    razonsocial VARCHAR(255) NOT NULL,
    nombre VARCHAR(100),
    apellido VARCHAR(100),
    ruc VARCHAR(20) NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: PedidoCompra
CREATE TABLE PedidoCompra (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nropedido VARCHAR(50) NOT NULL,
    idproveedor INT UNSIGNED NOT NULL,
    idtienda INT UNSIGNED NOT NULL,
    fechapedido DATE NOT NULL,
    estado INT NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idproveedor) REFERENCES Proveedor(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idtienda) REFERENCES Tienda(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: DetallePedidoCompra
CREATE TABLE DetallePedidoCompra (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idpedidocompra INT UNSIGNED NOT NULL,
    idropa INT UNSIGNED NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    cantidad INT NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idpedidocompra) REFERENCES PedidoCompra(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idropa) REFERENCES Ropa(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: FacturaCompra
CREATE TABLE FacturaCompra (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idpedidocompra INT UNSIGNED NOT NULL,
    fechafactura DATE NOT NULL,
    idtimbrado INT UNSIGNED NOT NULL,
    estado INT NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultimamodifcacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idpedidocompra) REFERENCES PedidoCompra(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idtimbrado) REFERENCES Timbrado(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: DetalleFacturaCompra
CREATE TABLE DetalleFacturaCompra (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idfacturacompra INT UNSIGNED NOT NULL,
    idropa INT UNSIGNED NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    cantidad INT NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idfacturacompra) REFERENCES FacturaCompra(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idropa) REFERENCES Ropa(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: Cliente
CREATE TABLE Cliente (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    razonsocial VARCHAR(255) NOT NULL,
    nombre VARCHAR(100),
    apellido VARCHAR(100),
    ruc VARCHAR(20) NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: PedidoVenta
CREATE TABLE PedidoVenta (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nropedido varchar(50) NOT NULL,
    idcliente INT UNSIGNED NOT NULL,
    idtienda INT UNSIGNED NOT NULL,
    fechapedido DATE NOT NULL,
    estado INT NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idcliente) REFERENCES Cliente(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idtienda) REFERENCES Tienda(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: DetallePedidoVenta
CREATE TABLE DetallePedidoVenta (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idpedidoventa INT UNSIGNED NOT NULL,
    idropa INT UNSIGNED NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    cantidad INT NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idpedidoventa) REFERENCES PedidoVenta(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idropa) REFERENCES Ropa(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: FacturaVenta
CREATE TABLE FacturaVenta (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idpedidoventa INT UNSIGNED NOT NULL,
    fechafactura DATE NOT NULL,
    idtimbrado INT UNSIGNED NOT NULL,
    estado INT NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idpedidoventa) REFERENCES PedidoVenta(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idtimbrado) REFERENCES Timbrado(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla: DetalleFacturaVenta
CREATE TABLE DetalleFacturaVenta (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idfacturaventa INT UNSIGNED NOT NULL,
    idropa INT UNSIGNED NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    cantidad INT NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fechaultmodificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idfacturaventa) REFERENCES FacturaVenta(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idropa) REFERENCES Ropa(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
