/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.entity.Ropa;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author yyy
 */
public class ArticuloCRUD extends javax.swing.JFrame {
    
    Ropa ropaPrueba = new Ropa(
    1, "Camiseta de algodón", 3, 2, "usuario123", LocalDateTime.now());

    List<Ropa> listaRopas = new ArrayList<>();
    /**
     * Creates new form ArticuloCRUD
     */
    public ArticuloCRUD() {
           initComponents();
    // Generar 10 artículos con datos de prueba
     // Generar 10 artículos de ropa con datos de prueba
        listaRopas.add(new Ropa(1, "Camiseta deportiva Nike con logo", 2, 1, "juan.perez", LocalDateTime.now()));
        listaRopas.add(new Ropa(2, "Jeans Levi's 501 Corte Recto", 3, 2, "ana.martinez", LocalDateTime.now().minusDays(1)));
        listaRopas.add(new Ropa(3, "Chaqueta de invierno Columbia", 4, 3, "pedro.sanchez", LocalDateTime.now().minusDays(2)));
        listaRopas.add(new Ropa(4, "Vestido largo de verano Mango", 1, 4, "laura.gomez", LocalDateTime.now().minusWeeks(1)));
        listaRopas.add(new Ropa(5, "Botines Timberland en cuero", 3, 5, "jose.fernandez", LocalDateTime.now().minusMonths(1)));
        listaRopas.add(new Ropa(6, "Pantalones deportivos Adidas", 2, 2, "maria.lopez", LocalDateTime.now().minusMonths(2)));
        listaRopas.add(new Ropa(7, "Camiseta de manga larga Ralph Lauren", 2, 1, "ricardo.martinez", LocalDateTime.now().minusDays(5)));
        listaRopas.add(new Ropa(8, "Sudadera con capucha Under Armour", 3, 2, "patricia.hernandez", LocalDateTime.now().minusDays(3)));
        listaRopas.add(new Ropa(9, "Pantalones cortos deportivos Nike", 1, 3, "luis.gomez", LocalDateTime.now().minusMonths(3)));
        listaRopas.add(new Ropa(10, "Abrigo de lana Burberry", 4, 5, "carlos.perez", LocalDateTime.now().minusWeeks(2)));


    // Configurar las columnas de la tabla
    String[] columnas = {"ID", "Nombre", "Categoría", "Descripción", "Usuario", "Fecha Últ. Modificación"};
    DefaultTableModel model = new DefaultTableModel(columnas, 0);

    // Llenar la tabla con los datos de los artículos
    for (Ropa ropa : listaRopas) {
        Object[] row = {
            ropa.getId(),
            ropa.getDescripcion(),
            ropa.getIdCategoria(),
            ropa.getIdTalla(),
            ropa.getUsuario(),
            ropa.getFechaUltModificacion()
        };
        model.addRow(row);
    }

    // Ordenar las filas de la tabla
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
    tbArticulo.setRowSorter(sorter);  // Asumiendo que tbArticulo es la tabla en tu interfaz

    // Establecer el modelo de la tabla
    tbArticulo.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscar = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbArticulo = new javax.swing.JTable();
        lblArticulo = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        lblDescripcion = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        txtDescripcion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblTalla = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        cbTalla = new javax.swing.JComboBox<>();
        cbCategoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        lblCategoria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCategoria.setText("Categoria:");

        tbArticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Remera", "M", "Verano"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Descripción", "Talla", "Categoria"
            }
        ));
        jScrollPane1.setViewportView(tbArticulo);

        lblArticulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblArticulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArticulo.setText("ARTICULO");

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblId.setText("Id:");

        txtId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/remove.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDescripcion.setText("Descripción:");

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("");
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/confirm.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("");
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setPreferredSize(new java.awt.Dimension(99, 68));
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblTalla.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTalla.setText("Talla:");

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBuscar.setText("Buscar:");

        cbTalla.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbTalla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Talla S", "Talla P", "Talla M", "Talla G" }));
        cbTalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTallaActionPerformed(evt);
            }
        });

        cbCategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Verano", "Invierno", "Otoño", "Primavera" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDescripcion)
                                    .addComponent(lblTalla)
                                    .addComponent(lblCategoria)
                                    .addComponent(lblId))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                                    .addComponent(txtDescripcion)
                                    .addComponent(cbTalla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                            .addComponent(txtBuscar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(lblArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescripcion))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTalla, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTalla))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategoria)
                            .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if (validarCampoID()) {
            if (Integer.parseInt(txtId.getText()) != ropaPrueba.getId()) {
                JOptionPane.showMessageDialog(this, "El articulo ingresado no existe", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            txtDescripcion.setText(ropaPrueba.getDescripcion());
            cbTalla.setSelectedIndex(ropaPrueba.getIdTalla());
            cbCategoria.setSelectedIndex(ropaPrueba.getIdCategoria());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        // Primero, validamos que todos los campos estén completos
        if (validarCampos()) {
            // Creamos el cliente con los datos de los campos de texto
            // Crear el objeto Proveedor
            int id = Integer.parseInt(txtId.getText());  // Convertir el texto a un número
            String descripcion = txtDescripcion.getText();
            int idtalla = cbTalla.getSelectedIndex();
            int idcategoria = cbCategoria.getSelectedIndex();
            String usuario = txtBuscar.getText(); // Suponiendo que "Buscar" es el campo de usuario

            // Crear el objeto proveedor
            Ropa ropa = new Ropa(id, descripcion, idtalla, idcategoria, usuario, LocalDateTime.now());


            // Aquí puedes agregar la lógica para guardar el cliente en la base de datos o en una lista
            // Por ejemplo, si tienes un servicio para ello:
            // clienteService.save(cliente);

            // Limpiar los campos
            txtId.setText("");
            txtDescripcion.setText("");
            cbTalla.setSelectedIndex(0);
            cbCategoria.setSelectedIndex(0);

            // Mostrar mensaje de éxito
            JOptionPane.showMessageDialog(this, "Articulo guardado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cbTallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTallaActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         if (validarCampoID()) {
            if (Integer.parseInt(txtId.getText()) != ropaPrueba.getId()) {
                JOptionPane.showMessageDialog(this, "El Articulo ingresado no existe", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(this, "Articulo eliminado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArticuloCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArticuloCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArticuloCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArticuloCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArticuloCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<String> cbTalla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblArticulo;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblTalla;
    private javax.swing.JTable tbArticulo;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables

      private boolean validarCampos() {
        // Comprobamos que todos los campos tengan contenido
    if (txtId.getText().trim().isEmpty() || 
        txtDescripcion.getText().trim().isEmpty() || String.valueOf(cbTalla.getSelectedIndex()).trim().isEmpty() || 
        String.valueOf(cbCategoria.getSelectedIndex()).trim().isEmpty()) {
        
        // Mostramos un mensaje de error si algún campo está vacío
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        return false; // Si algún campo está vacío, retorna false
    }
    return true; // Todos los campos están llenos
    }

    private boolean validarCampoID() {
        // Comprobamos que todos los campos tengan contenido
    if (txtId.getText().trim().isEmpty()) {
        
        // Mostramos un mensaje de error si algún campo está vacío
        JOptionPane.showMessageDialog(this, "El campo ID es necesario para buscar un articulo", "Error", JOptionPane.ERROR_MESSAGE);
        return false; // Si algún campo está vacío, retorna false
    }
    return true; // Todos los campos están llenos
    }

}
