/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.entity.Cliente;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author yyy
 */
public class ClienteCRUD extends javax.swing.JFrame {
    
    
   Cliente clientePrueba = new Cliente(
                1, 
                "Comercial XYZ S.A.", 
                "Carlos", 
                "Pérez", 
                "1234567890123", 
                "carlos.perez", 
                LocalDateTime.now()
        );
   
   List<Cliente> listaClientes = new ArrayList<>();
   
   
    
    /**
     * Creates new form Cliente
     */
    public ClienteCRUD() {
        initComponents();
        // Generar 10 clientes con datos de prueba
        listaClientes.add(new Cliente(1, "Comercial XYZ S.A.", "Carlos", "Pérez", "1234567890123", "carlos.perez", LocalDateTime.now()));
        listaClientes.add(new Cliente(2, "Tecnología Global S.A.", "Ana", "Martínez", "9876543210987", "ana.martinez", LocalDateTime.now().minusDays(1)));
        listaClientes.add(new Cliente(3, "Distribuciones Rápidas", "Luis", "Gómez", "1122334455667", "luis.gomez", LocalDateTime.now().minusWeeks(2)));
        listaClientes.add(new Cliente(4, "Servicios Financieros Alfa", "María", "López", "2233445566778", "maria.lopez", LocalDateTime.now().minusMonths(3)));
        listaClientes.add(new Cliente(5, "Soluciones Industriales", "José", "Fernández", "3344556677889", "jose.fernandez", LocalDateTime.now().minusMonths(6)));
        listaClientes.add(new Cliente(6, "Importadora Pérez", "Pedro", "Ramírez", "4455667788990", "pedro.ramirez", LocalDateTime.now().minusYears(1)));
        listaClientes.add(new Cliente(7, "Alimentos y Bebidas S.A.", "Laura", "Sánchez", "5566778899001", "laura.sanchez", LocalDateTime.now().minusDays(10)));
        listaClientes.add(new Cliente(8, "Construcciones del Sur", "Miguel", "Torres", "6677889900112", "miguel.torres", LocalDateTime.now().minusDays(15)));
        listaClientes.add(new Cliente(9, "Consultora Estratégica", "Patricia", "Hernández", "7788990011223", "patricia.hernandez", LocalDateTime.now().minusMonths(2)));
        listaClientes.add(new Cliente(10, "Tecnología y Servicios", "Ricardo", "Ramírez", "8899001122334", "ricardo.ramirez", LocalDateTime.now().minusWeeks(3)));
        String[] columnas = {"ID", "Razón Social", "Nombre", "Apellido", "RUC","Usuario", "Fecha Últ. Modificación"};
        DefaultTableModel model = new DefaultTableModel(columnas, 0);
        
        for (Cliente cliente : listaClientes) {
            Object[] row = {
                cliente.getId(),
                cliente.getRazonSocial(),
                cliente.getNombre(),
                cliente.getApellido(),
                cliente.getRuc(),
                cliente.getUsuario(),
                cliente.getFechaUltModificacion()
            };
            model.addRow(row);
        }
        
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tbCliente.setRowSorter(sorter);  // Asumiendo que tbCliente ya está definido en tu interfaz

        
        tbCliente.setModel(model);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCliente = new javax.swing.JTable();
        lblCliente = new javax.swing.JLabel();
        lblRuc = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtRuc = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        lblRazonSocial = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        txtRazonSocial = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        tbCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Tu hermana", "Karen", "Gimenez", "capiata", "9.235.941-1"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Razon Social", "Nombre", "Apellido", "Direccion", "Ruc"
            }
        ));
        jScrollPane1.setViewportView(tbCliente);

        lblCliente.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCliente.setText("CLIENTE");

        lblRuc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRuc.setText("Ruc:");

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblId.setText("Id:");

        txtRuc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/remove.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblRazonSocial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRazonSocial.setText("Razón Social:");

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("");
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        txtRazonSocial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/confirm.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("");
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setPreferredSize(new java.awt.Dimension(99, 68));
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombre.setText("Nombre:");

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBuscar.setText("Buscar:");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblApellido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblApellido.setText("Apellido:");

        txtApellido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRazonSocial)
                    .addComponent(lblId)
                    .addComponent(lblApellido)
                    .addComponent(lblNombre)
                    .addComponent(lblRuc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRuc, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRazonSocial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellido))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRuc)
                            .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditar)
                            .addComponent(btnEliminar)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if (validarCampoID()) {
            if (Integer.parseInt(txtId.getText()) != clientePrueba.getId()) {
                JOptionPane.showMessageDialog(this, "El cliente ingresado no existe", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            txtRazonSocial.setText(clientePrueba.getRazonSocial());
            txtNombre.setText(clientePrueba.getNombre());
            txtApellido.setText(clientePrueba.getApellido());
            txtRuc.setText(clientePrueba.getRuc());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        // Primero, validamos que todos los campos estén completos
        if (validarCampos()) {
            // Creamos el cliente con los datos de los campos de texto
            // Crear el objeto Proveedor
            int id = Integer.parseInt(txtId.getText());  // Convertir el texto a un número
            String razonSocial = txtRazonSocial.getText();
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String ruc = txtRuc.getText();
            String usuario = txtBuscar.getText(); // Suponiendo que "Buscar" es el campo de usuario

            // Crear el objeto proveedor
            Cliente cliente = new Cliente(id, razonSocial, nombre, apellido, ruc, usuario, LocalDateTime.now());


            // Aquí puedes agregar la lógica para guardar el cliente en la base de datos o en una lista
            // Por ejemplo, si tienes un servicio para ello:
            // clienteService.save(cliente);

            // Limpiar los campos
            txtId.setText("");
            txtRazonSocial.setText("");
            txtNombre.setText("");
            txtApellido.setText("");
            txtRuc.setText("");

            // Mostrar mensaje de éxito
            JOptionPane.showMessageDialog(this, "Cliente guardado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (validarCampoID()) {
            if (Integer.parseInt(txtId.getText()) != clientePrueba.getId()) {
                JOptionPane.showMessageDialog(this, "El cliente ingresado no existe", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(this, "Cliente eliminado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
                                   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JLabel lblRuc;
    private javax.swing.JTable tbCliente;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtRuc;
    // End of variables declaration//GEN-END:variables

    private boolean validarCampos() {
        // Comprobamos que todos los campos tengan contenido
    if (txtId.getText().trim().isEmpty() || txtRazonSocial.getText().trim().isEmpty() || 
        txtNombre.getText().trim().isEmpty() || txtApellido.getText().trim().isEmpty() || 
        txtRuc.getText().trim().isEmpty()) {
        
        // Mostramos un mensaje de error si algún campo está vacío
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        return false; // Si algún campo está vacío, retorna false
    }
    return true; // Todos los campos están llenos
    }

    private boolean validarCampoID() {
        // Comprobamos que todos los campos tengan contenido
    if (txtId.getText().trim().isEmpty()) {
        
        // Mostramos un mensaje de error si algún campo está vacío
        JOptionPane.showMessageDialog(this, "El campo ID es necesario para buscar un cliente", "Error", JOptionPane.ERROR_MESSAGE);
        return false; // Si algún campo está vacío, retorna false
    }
    return true; // Todos los campos están llenos
    }

}
