/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.controllers.ProveedorController;
import com.entity.Proveedor;
import com.service.ProveedorService;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Nice
 */
public class ProveedorCRUD extends javax.swing.JFrame {
        
    //TODO Eliminar datos de pruebas 
    Proveedor proveedorTest = new Proveedor(
            1, 
            "Karen SRL", 
            "Karen", 
            "Gimenez", 
            "985441-5", 
            "kgimenez", 
            LocalDateTime.now());

        List<Proveedor> proveedores = new ArrayList<>();

    public ProveedorCRUD() {
        initComponents();
        
        proveedores.add(new Proveedor(1, "Comercial ABC S.A.", "Carlos", "Pérez", "123456789", "carlos.perez", LocalDateTime.now()));
        proveedores.add(new Proveedor(2, "Distribuciones XYZ", "Ana", "Martínez", "987654321", "ana.martinez", LocalDateTime.now()));
        proveedores.add(new Proveedor(3, "Productos El Sol", "Luis", "González", "456789123", "luis.gonzalez", LocalDateTime.now()));
        proveedores.add(new Proveedor(4, "Tecnologías Globales", "Marta", "López", "321654987", "marta.lopez", LocalDateTime.now()));
        proveedores.add(new Proveedor(5, "Alimentos del Valle", "Juan", "Rodríguez", "159753486", "juan.rodriguez", LocalDateTime.now()));
        proveedores.add(new Proveedor(6, "Construcciones Progreso", "Sofía", "Hernández", "258369741", "sofia.hernandez", LocalDateTime.now()));
        proveedores.add(new Proveedor(7, "Soluciones Eficientes", "Pedro", "Gómez", "753951456", "pedro.gomez", LocalDateTime.now()));
        proveedores.add(new Proveedor(8, "Servicios Integrales", "Elena", "Vázquez", "369258147", "elena.vazquez", LocalDateTime.now()));
        proveedores.add(new Proveedor(9, "Insumos Industriales", "Roberto", "Sánchez", "147852369", "roberto.sanchez", LocalDateTime.now()));
        proveedores.add(new Proveedor(10, "Farmacéutica Delta", "Clara", "Jiménez", "258147369", "clara.jimenez", LocalDateTime.now()));
        
        String[] columnas = {"ID", "Razón Social", "Nombre", "Apellido", "RUC", "Usuario", "Fecha Últ. Modificación"};
        DefaultTableModel model = new DefaultTableModel(columnas, 0);
        
        
        for (Proveedor proveedor : proveedores) {
            Object[] row = {proveedor.getId(), proveedor.getRazonSocial(), proveedor.getNombre(), proveedor.getApellido(),
                            proveedor.getRuc(), proveedor.getUsuario(), proveedor.getFechaUltModificacion()};
            model.addRow(row);
        }
        
        
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tbProveedor.setRowSorter(sorter);  // Asumiendo que tbProveedor ya está definido en tu interfaz

        
        tbProveedor.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProveedor = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblRazonSocial = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblRUC = new javax.swing.JLabel();
        txtRUC = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblId1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProveedor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmProveedor"); // NOI18N

        lblProveedor.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProveedor.setText("PROVEEDOR");

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblId.setText("Id:");

        txtId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblRazonSocial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRazonSocial.setText("Razon Social:");

        txtRazonSocial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombre.setText("Nombre:");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblApellido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblApellido.setText("Apellido:");

        txtApellido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblRUC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRUC.setText("RUC:");

        txtRUC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/remove.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("");
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/confirm.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("");
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setPreferredSize(new java.awt.Dimension(99, 68));
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblId1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblId1.setText("Buscar:");

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        tbProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "tu hermana", "Karen", "Gimenez", "9.235.941-1"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Razon Social", "Nombre", "Apellido", "RUC"
            }
        ));
        jScrollPane1.setViewportView(tbProveedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRazonSocial)
                    .addComponent(lblNombre)
                    .addComponent(lblApellido)
                    .addComponent(lblRUC)
                    .addComponent(lblId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                        .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtRazonSocial, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtRUC)))
                .addGap(11, 11, 11)
                .addComponent(lblId1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(lblProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblId))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblId1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRazonSocial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRUC))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if (validarCampoID()) {
            if (Integer.parseInt(txtId.getText()) != proveedorTest.getId()) {
                JOptionPane.showMessageDialog(this, "El proveedor ingresado no existe", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            txtRazonSocial.setText(proveedorTest.getRazonSocial());
            txtNombre.setText(proveedorTest.getNombre());
            txtApellido.setText(proveedorTest.getApellido());
            txtRUC.setText(proveedorTest.getRuc());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Primero, validamos que todos los campos estén completos
        if (validarCampos()) {
            // Creamos el proveedor con los datos de los campos de texto
            // Crear el objeto Proveedor
            int id = Integer.parseInt(txtId.getText());  // Convertir el texto a un número
            String razonSocial = txtRazonSocial.getText();
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String ruc = txtRUC.getText();
            String usuario = txtBuscar.getText(); // Suponiendo que "Buscar" es el campo de usuario

            // Crear el objeto proveedor
            Proveedor proveedor = new Proveedor(id, razonSocial, nombre, apellido, ruc, usuario, LocalDateTime.now());


            // Aquí puedes agregar la lógica para guardar el proveedor en la base de datos o en una lista
            // Por ejemplo, si tienes un servicio para ello:
            // proveedorService.save(proveedor);

            // Limpiar los campos
            txtId.setText("");
            txtRazonSocial.setText("");
            txtNombre.setText("");
            txtApellido.setText("");
            txtRUC.setText("");

            // Mostrar mensaje de éxito
            JOptionPane.showMessageDialog(this, "Proveedor guardado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
       
        if (validarCampoID()) {
            if (Integer.parseInt(txtId.getText()) != proveedorTest.getId()) {
                JOptionPane.showMessageDialog(this, "El proveedor ingresado no existe", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(this, "Proveedor eliminado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProveedorCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblId1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblRUC;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JTable tbProveedor;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRUC;
    private javax.swing.JTextField txtRazonSocial;
    // End of variables declaration//GEN-END:variables

private boolean validarCampos() {
    // Comprobamos que todos los campos tengan contenido
    if (txtId.getText().trim().isEmpty() || txtRazonSocial.getText().trim().isEmpty() || 
        txtNombre.getText().trim().isEmpty() || txtApellido.getText().trim().isEmpty() || 
        txtRUC.getText().trim().isEmpty()) {
        
        // Mostramos un mensaje de error si algún campo está vacío
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        return false; // Si algún campo está vacío, retorna false
    }
    return true; // Todos los campos están llenos
}

private boolean validarCampoID() {
    // Comprobamos que todos los campos tengan contenido
    if (txtId.getText().trim().isEmpty()) {
        
        // Mostramos un mensaje de error si algún campo está vacío
        JOptionPane.showMessageDialog(this, "El campo ID es necesario para buscar un proveedor", "Error", JOptionPane.ERROR_MESSAGE);
        return false; // Si algún campo está vacío, retorna false
    }
    return true; // Todos los campos están llenos
}

}
