/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.controllers.PedidoCompraController;
import com.entity.PedidoCompra;
import com.repository.PedidoCompra.PedidoCompraRepository;
import com.service.PedidoCompraService;
import java.util.List;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jen
 */
public class ReportePedidos extends javax.swing.JFrame {
    
    PedidoCompraRepository pedidoCompraRepository = new PedidoCompraRepository();
    PedidoCompraService pedidoCompraService = new PedidoCompraService(pedidoCompraRepository);
    PedidoCompraController pedidoCompraController = new PedidoCompraController(pedidoCompraService);
    /**
     * Creates new form ReportePedidos
     */
    public ReportePedidos() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("REPORTE DE PEDIDOS REALIZADOS");

        jLabel1.setText("ID Pedido");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "ID Cliente", "Tienda", "Fecha", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
        String inputText = jTextField1.getText().trim();
        
            if (inputText.isEmpty()) {
                cargarTabla();
            } else {
                try {
                    int pedidoId = Integer.parseInt(inputText); 

                    Optional<PedidoCompra> pedidoOpt = pedidoCompraController.obtenerPedidoCompra(pedidoId);
                    pedidoOpt.ifPresentOrElse(pedido -> {
                    String[] columnNames = {"ID", "Nro. Pedido", "ID Proveedor", "ID Tienda", "Fecha Pedido", "Estado", "Usuario", "Fecha Mod."};

                    DefaultTableModel model = new DefaultTableModel(columnNames, 0);

                    model.addRow(new Object[]{
                        pedido.getId(),
                        pedido.getNroPedido(),
                        pedido.getIdProveedor(),
                        pedido.getIdTienda(),
                        pedido.getFechaPedido(),
                        pedido.getEstado(),
                        pedido.getUsuario(),
                        pedido.getFechaUltModificacion()
                    });

                        jTable1.setModel(model);
                    }, () -> {
                        JOptionPane.showMessageDialog(null, "Pedido no encontrado");
                    });
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Por favor, ingrese un ID válido");
                }
            }
        }
    }

        public void cargarTabla(){
        List<PedidoCompra> pedidoCompraList = pedidoCompraController.listarPedidoCompra();
        if (pedidoCompraList.isEmpty()) {
            return;
        }
        String[] columnNames = {"ID", "Nro. Pedido", "ID Proveedor", "ID Tienda", "Fecha Pedido", "Estado", "Usuario", "Fecha Mod."};

        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        for (PedidoCompra pedido : pedidoCompraList) {
            model.addRow(new Object[]{
                        pedido.getId(),
                        pedido.getNroPedido(),
                        pedido.getIdProveedor(),
                        pedido.getIdTienda(),
                        pedido.getFechaPedido(),
                        pedido.getEstado(),
                        pedido.getUsuario(),
                        pedido.getFechaUltModificacion()
                    });
        }

        // Set the table model to jTable1
        jTable1.setModel(model);
    }//GEN-LAST:event_jTextField1KeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
